### ISSUE TITLE
Scheduled scans not working anymore

### ISSUE THREAD

**Issue by DartLazer** [DartLazer/WhoIsHomeUI#21]
My scheduled scans are not being triggered anymore since v 0.3

Didn't find the reason yet.

Anyone else experiencing this? @babanomania @spandan13

**Comment by babanomania** [comment]
Check the django admin background jobs section, usually the error logs can be seen there

**Comment by babanomania** [comment]
i just checked, jobs not triggering happening for me also.
no logs anywhere, very strange.

I'm removing the docker volume and starting afresh to test

**Comment by babanomania** [comment]
so the problem is the time inside the container is UTC and not in the correct timezone, so the job scheduler is messed up.
i'm testing with the below docker-compose.yml, timezone seems to be picked up correctly now

```yml
version: "3.8"

services:
  web:
    network_mode: "host"
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:${WHOIH_PORT:-8000}"
    environment:
      - TZ=${WHOIH_TZ}
      - DJANGO_TZ=${WHOIH_TZ}
      - DJANGO_DBPATH=/dbstore/db.sqlite3
    restart: always
    volumes:
      - dbstore:/dbstore

volumes:
  dbstore:
```

**Comment by babanomania** [comment]
still no luck 👎

**Comment by spandan13** [comment]
> Anyone else experiencing this? @babanomania @spandan13 

Same issue here. Unable to find what's causing it

**Comment by DartLazer** [comment]
When I add mysite to the volumes again its working for me.

**Comment by DartLazer** [comment]
The background tasks library has been causing issues for me in other projects too.  For example it's not compatible with django 4.

I'm considering setting up some sort of crontab that will run a django command file or fully implement celery (which will make the build heavier for sure)

I will have a look when I get back home later today!

**Comment by DartLazer** [comment]
I'm gonna remove django background tasks all together and make a setup with crontab since we only have 1 simple scheduled task.

Should keep it simple

**Comment by babanomania** [comment]
Okay, good idea

**Comment by DartLazer** [comment]
I fixed it locally will push later today.
Created a python management command that will be triggered by the cron in the docker container

**Comment by spandan13** [comment]
Were you able to try using slim-buster?

**Comment by babanomania** [comment]
> @babanomania @spandan13 Spent the whole afternoon on this...
> 
> I made a solution with a second container that runs cronjobs and connects to page /scan/ which will trigger a scan.
> 
> I tried with the alpine build, which worked great on both of my desktop but failed on both raspberry pi's ...
> 
> That's why I ended up using the python-buster3 image again. I hope you guys have enough space for that. Another solution woudl be welcome too

so far the new solution works good, i'll try again to make it work on alpine .
Ideally the scheduler container should work with alpine

**Comment by spandan13** [comment]
@DartLazer The 2nd container is only for running a cronjob? Is it possible to run the cronjob directly on the host?

**Comment by DartLazer** [comment]
Well no the idea behind docker containers is that every container runs one command so maybe yes you technically could but I'd prefer it this way.

The strange thing is @babanomania that the alpine image works brilliantly on desktop. I used the following setup:
```Dockerfile
ARG WHOIH_PORT
FROM alpine:latest
ARG WHOIH_PORT
RUN apk --no-cache add curl
RUN echo "* * * * * curl http://localhost:${WHOIH_PORT}/scan/" | crontab -e
CMD ["crond", "-f"]
```

It only used 8 mb on my ubuntu system.

I reckon it once again has something to do with the alpine arm7 build, which you mentioned was causing issues for arp-scan as well.

Another option would be to find another way to get the page on that port. wget or something else would be sufficient to. We could then get it up in alpine and only use8 mb @spandan13 .

I'm done for today but if someone wants to try please go ahead!

**Comment by babanomania** [comment]
@DartLazer try this

```yaml
version: "3.8"

services:
  web:
    network_mode: "host"
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:${WHOIH_PORT:-8000}"
    environment:
      - DJANGO_TZ=${WHOIH_TZ}
      - DJANGO_DBPATH=/dbstore/db.sqlite3
    restart: always
    volumes:
      - dbstore:/dbstore

  scanner:
    image: curlimages/curl
    command: "curl -s http://web:${WHOIH_PORT}/scan/ && sleep 60s"

volumes:
  dbstore:
```

**Comment by spandan13** [comment]
What if for the main container instead of having the command set to the python webserver, we instead use a entrypoint script there and add `service start cron` and then the python command below it? Will try to test this

**Comment by babanomania** [comment]
> What if for the main container instead of having the command set to the python webserver, we instead use a entrypoint script there and add `service start cron` and then the python command below it? Will try to test this

 We don't even need cron, for entrypoint, just curl and sleep 60s

**Comment by babanomania** [comment]
> @DartLazer try this
> 
> ```yaml
> version: "3.8"
> 
> services:
>   web:
>     network_mode: "host"
>     build: .
>     command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:${WHOIH_PORT:-8000}"
>     environment:
>       - DJANGO_TZ=${WHOIH_TZ}
>       - DJANGO_DBPATH=/dbstore/db.sqlite3
>     restart: always
>     volumes:
>       - dbstore:/dbstore
> 
>   scanner:
>     image: curlimages/curl
>     command: "curl -s http://web:${WHOIH_PORT}/scan/ && sleep 60s"
> 
> volumes:
>   dbstore:
> ```

@spandan13 check this

**Comment by DartLazer** [comment]
Man that looks sexy.  Does it work?

**Comment by babanomania** [comment]
> Man that looks sexy. Does it work?

its works fine on my PiZero2W

**Comment by DartLazer** [comment]
Maybe at a restart always?  And then we can pull?

**Comment by babanomania** [comment]
@DartLazer yes you're right, below is the one which works

```yaml
version: "3.8"

services:
  web:
    network_mode: "host"
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:${WHOIH_PORT:-8000}"
    environment:
      - DJANGO_TZ=${WHOIH_TZ}
      - DJANGO_DBPATH=/dbstore/db.sqlite3
    restart: always
    volumes:
      - dbstore:/dbstore

  scanner:
    image: curlimages/curl
    command: "sleep 60s && curl -s http://web:${WHOIH_PORT}/scan/"
    restart: always

volumes:
  dbstore:
```
